const captchaDivOuter = document.createElement('div');
captchaDivOuter.classList = 'hcpt';
captchaDivOuter.innerHTML = `<div class="hcptFsh"><div class="hcpttl">Click All Image Contains A Bus</div><div class="himg"></div></div><div class="hcptcha"><div class="hcptchaI">  <h2>Are You A Robot?</h2>  <p>please prove you're a human</p></div><button class="hcptchaBtn">Verify</button></div>`;
const captchaDivOuterStyle = document.createElement('style');
captchaDivOuterStyle.innerHTML = `.hcpt{position: fixed;top: 0;left: 0;right: 0;height: 100%;width:100%;background: rgba(0,0,0,.3);display: flex;justify-content: center;align-items: center;font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif !important;user-select: none;transition: opacity .4s ease, visibility .4s ease;z-index: 98989898989898;opacity: 0;visibility: hidden;}.hcpt .hcptcha{background: #fffdfc;padding: 15px 20px;position: absolute;bottom: -200px;border-radius: 20px 20px 0 0;display: flex;transition: bottom .3s;border: 1px solid rgba(0,0,0,.1);border-bottom: none;}.hcpt .hcptcha .hcptchaI{width: 100%;}.hcpt .hcptcha .hcptchaI h2{font-size: 19px;}.hcpt .hcptcha .hcptchaI p{font-size: 95%;}.hcpt .hcptcha .hcptchaBtn{background: #14046e;border: none;border-radius: 100px;padding: 0 20px;width: 100px;height: 46px;font-size: 15px;font-weight: bold;color: #fffdfc;cursor: pointer;display: inline-flex;align-items: center;justify-content: center;}.hcpt .himg{max-height: 277px;display: grid;place-content: center;grid-template-columns: auto auto auto;background: #fffdfc;border-radius: 10px;overflow: hidden;padding: 9px;border: 1px solid rgba(0,0,0,.1);gap: 4px;margin: 0;opacity: 0;visibility: hidden;transition: opacity .4s ease, visibility .4s ease;}.hcpt .himg div{border-radius: 5px;padding: 0px !important;margin: 0px !important;gap: 0px !important;height: 90px;max-width: 90px;overflow: hidden;}.hcpt .himg div img:hover{transform: scale(1.1);}.hcpt .himg div img{border-radius: 5px;transition: transform .2s;padding: 0px !important;height: 90px;margin: 0px !important;max-width: 90px;gap: 0px !important;}.hcpt .hcpttl{background: #14046e;color: #fffdfc;font-size: 16px;border-radius: 10px 10px 0 0;padding: 6px 10px;width: max-content;opacity: 0;visibility: hidden;transition: opacity .3s, visibility .3s;}.hcpt .hcptFsh{display: grid;place-items: center;grid-template-columns:auto;}@media screen and (min-width:500px){.hcpt .hcptcha{width: 400px;}}@media screen and (max-width:500px) {.hcpt .hcptcha{left: 0;right: 0;}}`;
document.head.appendChild(captchaDivOuterStyle);
document.body.appendChild(captchaDivOuter);
const captchaHandItems = document.querySelector('.himg');
const captchaHumanDatas = () => {const captchaData = [`<div class="oihg"><img src='https://i.postimg.cc/4dGVpxcg/images.jpg'></div>`,`<div class="oihgNo"><img src='https://i.postimg.cc/tg39nqyW/images.jpg'></div>`,`<div class="oihgNo"><img src='https://i.postimg.cc/5t2yXkWc/images.jpg'></div>`,`<div class="oihgNo"><img src='https://i.postimg.cc/XvHLThkQ/download.jpg'></div>`,`<div class="oihg"><img src='https://i.postimg.cc/4dGVpxcg/images.jpg'></div>`,`<div class="oihgNo"><img src='https://i.postimg.cc/XvHLThkQ/download.jpg'></div>`,`<div class="oihg"><img src='https://i.postimg.cc/4dGVpxcg/images.jpg'></div>`,`<div class="oihgNo"><img src='https://i.postimg.cc/XvHLThkQ/download.jpg'></div>`,`<div class="oihgNo"><img src='https://i.postimg.cc/tg39nqyW/images.jpg'></div>`];return captchaData[Math.floor(Math.random() * captchaData.length)];};
captchaHandItems.innerHTML = `${captchaHumanDatas()}${captchaHumanDatas()}${captchaHumanDatas()}${captchaHumanDatas()}${captchaHumanDatas()}${captchaHumanDatas()}${captchaHumanDatas()}${captchaHumanDatas()}${captchaHumanDatas()}`;
const captchaOuter = document.querySelector('.hcpt'),captchaBtn = document.querySelector('.hcptchaBtn'),captchaInner = document.querySelector('.hcptcha'),captchaDataText = document.querySelector('.hcpttl');
captchaBtn.addEventListener('click', () => {captchaBtn.innerHTML = 'Verifying..';captchaHandItems.style.opacity = '1';captchaHandItems.style.visibility = 'visible';captchaDataText.style.opacity = '1';captchaDataText.style.visibility = 'visible';});
let captchaClick = 0;
const captchaCheck = () => {const oihg = document.querySelectorAll('.oihg');const fsdghc = [];Array.from(oihg).forEach((e) => {fsdghc.push(e);if (fsdghc.length < 1) {captchaDataText.innerText = 'Error: reload to continue'}e.addEventListener('click', () => {captchaClick++;if (captchaClick >= fsdghc.length) {captchaBtn.innerHTML = 'Verifyed!';setTimeout(() => {captchaBtn.innerHTML = 'Closing..';}, 1000);setTimeout(() => {captchaOuter.style.opacity = '0';captchaOuter.style.visibility = 'hidden';captchaDataText.style.opacity = '0';captchaDataText.style.visibility = 'hidden';captchaInner.style.bottom = '-200px';localStorage.setItem('verifyed', true);captchaDivOuterStyle.remove();captchaDivOuter.remove();}, 2500);}});});};
let captchaClickNot = 0;
const captchaNot = () => {
const oihgO = document.querySelectorAll('.oihgNo');
Array.from(oihgO).forEach((e) => {e.addEventListener('click', () => {captchaClickNot++;if (captchaClickNot >= 3) {captchaBtn.innerHTML = 'Error';setTimeout(() => {    captchaBtn.innerHTML = 'Verify';}, 1000);captchaOuter.style.opacity = '1';captchaOuter.style.visibility = 'visible';captchaInner.style.bottom = '0';captchaHandItems.style.opacity = '0';captchaHandItems.style.visibility = 'hidden';captchaDataText.style.opacity = '0';captchaDataText.style.visibility = 'hidden';captchaClick = 0;captchaClickNot = 0;}});});};
document.addEventListener('DOMContentLoaded', () => {if (!localStorage.getItem('verifyed')) {captchaOuter.style.opacity = '1';captchaOuter.style.visibility = 'visible';captchaInner.style.bottom = '0';captchaCheck();captchaNot();}else{captchaDivOuter.remove();captchaDivOuterStyle.remove();}});
